[package]
version = "0.1.0"
name = "brotli-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = { version = "6.0.0-beta.1" }
brotli-decompress = { path = "../lib" }
